JuliaDocs/DocStringExtensions.jl

- src/DocStringExtensions.jl
- src/abbreviations.jl
- src/utilities.jl
- test/runtests.jl
Print "simplified" versions of method signatures. Simplifications include: no `TypeVar`s, types, or keyword values.
> Implement simple signature printing

- src/DocStringExtensions.jl
Adds an introductory note related to the uses of the package as well as a simple example of how to use the `signatures` abbreviation.
> Expand introductory documentation for module

- src/utilities.jl
- test/tests.jl
Fixes #14. `methods` when applied to functions with signatures that contain `Union` types with concrete parameters returns duplicated `Method` objects. Remove the dups by collecting into a `Set` instead of a `Vector`.
> Deduplicate methods

- docs/make.jl
- docs/src/index.md
- src/DocStringExtensions.jl
- src/abbreviations.jl
- src/mock.jl
- src/templates.jl
- src/utilities.jl
- test/templates.jl
- test/tests.jl
Fixes #22. (cc @sivark if you're still interested in having docstring templates. The included tests and docs should provide enough explanation into how to go about using `@template`, let me know if there's anything that's unclear.)
Implements a `@template` macro used to define 'template' docstrings that can be applied to different categories of docstrings on a per-module basis.
> Docstring templates

- src/utilities.jl
Internal method compression was changed in JuliaLang/julia#20933 and is the cause of the current nightly failures. This PR should fix the issue here.
> Fix error in method introspection on 0.6

- REQUIRE
- src/abbreviations.jl
- test/tests.jl
This fixes the deprecation warnings on 0.6. Note though that the tests won't pass here until #27 is merged.
> Update type declaration syntax for 0.6

- .travis.yml
- REQUIRE
- appveyor.yml
- docs/make.jl
- src/DocStringExtensions.jl
- src/abbreviations.jl
- src/mock.jl
- src/templates.jl
- src/utilities.jl
- test/runtests.jl
- test/templates.jl
- test/tests.jl
Awaiting https://github.com/JuliaDocs/DocStringExtensions.jl/issues/35 decision.
BTW, I also tried to fix the `current_module` depwarns using `@__MODULE__`, but that didn't work straight away; not sure why yet.
Closes #35
> Drop support for 0.4 and 0.5, fix `type` and `immutable` depwarns

- src/templates.jl
- src/utilities.jl
- test/templates.jl
- test/tests.jl
Fixes  #32.
~~I must say I don't completely understand the test set. Could you show me how to add more of an integration test of the functionality of `$(SIGNATURES)` for a function that takes `UnionAll` arguments?~~
> Fix SIGNATURES for methods with UnionAll arguments

- src/utilities.jl
- test/tests.jl
I found [a snippet in Base](https://github.com/JuliaLang/julia/blob/3b45cdc9aab03850ee57f52c7b2389723f0811e8/base/replutil.jl#L572-L576) that might avoid the whole signature thing when trying to find out what the keyword arguments of a method are. It seems to fix the UnionAll issue without breaking tests. @tkoolen would you be willing to stress test this a bit, to make sure I haven't broken anything?
> Fix keywords() for UnionAll

- REQUIRE
- src/utilities.jl
- test/runtests.jl
- test/tests.jl
> Backports for 0.4.2

- src/abbreviations.jl
https://github.com/JuliaLang/julia/pull/25622 introduces a new function called `name` that replaces `module_name` and a couple other things. This package is using `name` as a loop variable and comparing that against the result of (what will be) a call to the `name` function, which results in an error when building documentation. This PR simply renames the loop variable to avoid this conflict.
It would be great if we could get this in ASAP, since it's blocking the Base PR.
> Rename loop variable to avoid conflict

- REQUIRE
- src/utilities.jl
- test/tests.jl
https://github.com/JuliaLang/Compat.jl/pull/520
> contains(haystack, needle) -> occursin(needle, haystack)

- src/templates.jl
- src/utilities.jl
- test/tests.jl
This fixes a deprecation warning on Julia 0.7 and is fully backwards compatible with 0.6.
> Use Core.eval instead of eval

- .travis.yml
Ref: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Use VMs instead of container-based builds

- docs/make.jl
- docs/src/index.md
- docs/src/internals.md
The only things that are actually part of the public API are the abbreviations and the `@template` macro, but the autodocs block was capturing all docstrings. All of these are now "demoted" to be internal:
```
DocStringExtensions.Abbreviation
DocStringExtensions.DocStringTemplate
DocStringExtensions.FunctionName
DocStringExtensions.License
DocStringExtensions.MethodList
DocStringExtensions.MethodSignatures
DocStringExtensions.ModuleExports
DocStringExtensions.ModuleImports
DocStringExtensions.Readme
DocStringExtensions.TypeDefinition
DocStringExtensions.TypeFields
DocStringExtensions.TypedMethodSignatures
DocStringExtensions.alltypesigs
DocStringExtensions.arguments
DocStringExtensions.cleanpath
DocStringExtensions.comparemethods
DocStringExtensions.format
DocStringExtensions.getmethods …
```
> Move some docstrings to internals page

- docs/Showcase/src/Showcase.jl
- docs/src/showcase.md
- src/abbreviations.jl
- src/utilities.jl
- test/TestModule/M.jl
- test/tests.jl
> Fix typed signatures parametric types

- .gitignore
- src/abbreviations.jl
- src/templates.jl
- test/TestModule/M.jl
- test/templates.jl
- test/tests.jl
This moves the expansion of templates from macro expansion time to later on. This allows us to avoid having to search through expressions looking for the actual expression type since those may be hidden by "decorator" macros. It also handles cases where `@doc` is used on a string macro docstring, such as
@doc raw"..." f(x) = x
Implementation is based on a new internal abbreviation type called `Template` which gets prepended and appended to docstrings in modules where templates are available. Then, during formatting, we expand these `Template` abbreviations into there definitions.
Fixes #73.
> Move template expansion to "format-time"

- Project.toml
This should fix Documenters test on Julia master: https://github.com/JuliaCI/NanosoldierReports/blob/303a819e120eac6b87b3c74c18c024ae0359e457/pkgeval/by_hash/3573793_vs_c4acbf9/logs/Documenter/1.6.0-DEV-4978cd5a4f.log#L672
Edit: And DocStringExtensions.jl itself too: https://github.com/JuliaCI/NanosoldierReports/blob/303a819e120eac6b87b3c74c18c024ae0359e457/pkgeval/by_hash/3573793_vs_c4acbf9/logs/DocStringExtensions/1.6.0-DEV-4978cd5a4f.log#L68
> Set version to 0.8.3.

- .travis.yml
- appveyor.yml
To make sure that we're actually testing on the latest release etc.
I also added (Linux) builds for 1.{1,2,3,4}. My argument here is that, since DocStringExtensions can get loaded behind the scenes in packages, we should be a bit more careful and make sure it is actually working on all possible Julia versions (up to a minor version anyhow).
> Update Julia versions on CI

- Project.toml
- src/DocStringExtensions.jl
- src/utilities.jl
I assume it was probably an artifact of converting to a `Project.toml`. Doesn't need `Pkg`, `Test`, or `Markdown` for the actual dependencies of the package. Drops `0.7` support, that's old enough that I don't feel it needs further support. Also moves the `LibGit2` import to an easier to find location at the top of the package.
> Move test deps out of `[deps]`.

- Project.toml
- src/abbreviations.jl
- src/utilities.jl
It looks like ~https://github.com/JuliaLang/julia/pull/41018~ https://github.com/JuliaLang/julia/pull/40741 removed the `.abstract` field from `DataType`, so DocStringExtensions is currently broken on nightly because of that. But I think the local `isabstracttype` and `isbitstype` definitions are some pre-1.0 leftovers -- functions with the same name are available in Base -- so it should be safe to just remove them.
`ismutabletype` was added in 1.7 (https://github.com/JuliaLang/julia/pull/39037), so we need a local version of it if it is not defined in `Base`.
> Remove is(abstract|bits)type functions

- docs/Project.toml
This PR fixes the version of Documenter.jl.
related: https://github.com/JuliaArrays/StaticArrays.jl/issues/870
> Fix the version of documenter

- .github/workflows/ci.yml
- src/utilities.jl
- test/tests.jl
This PR should address the issues raised in #120. Currently, long docstrings can become unwieldy to view in the repl. For example, in a package I am developing, this is the first part of the docstring for the function `differentiate!`:
```julia
differentiate!(x::Vector{Float64}, ν::Vector{Float64}, λ::Vector{Float64}, A::Matrix{Float64}, B::Matrix{Float64}, dx::Vector{Float64}, diffmodel::DifferentiableModel, optimizer; modifications, use_analytic, scale_output)
```
The more types and/or arguments are used, the more difficult it becomes to see what the function signature is. JuliaFormatter.jl breaks docstrings into multiple lines if they are too long. This PR mimics this behavior, so that the docstring for `differentiate!` becomes:
```julia
differentiate!(
x::Vector{Float64}, …
```
> Break long docstrings into multiple lines

- src/abbreviations.jl
- test/tests.jl
Older Windows versions of Julia used to have reversed ordering of arguments in the expressions that were processed, this has clearly been fixed in 1.8 and above, so make those conditions version dependant.
> Fix ordering of arguments on newer Windows versions

- src/utilities.jl
- test/tests.jl
The `kwsorter` field has been removed from the method table and there seems to be a new `#ctor-self#` argument that should be filtered out. Makes tests pass on master
> fix kw handling and filter out a new internal symbol from arguments 

- src/abbreviations.jl
- test/tests.jl
For `$FIELDS`/`$TYPEDFIELDS` templates, put the field description on the same line as the field name.
Example:
- `x::String`
- `y::Int`: Unlike the `x` field this field has been documented.
- `z::Array{Any, 1}`: Another documented field.
Fixes #63
> Condense $FIELDS template

- src/abbreviations.jl
Sorry, I've just realized that there was a bug in #136 that still introduced the newline after the field name and before its description. Now it should be fixed.
> Fix extra newline before field description

- src/utilities.jl
- test/tests.jl
For me this fixes #102
Problematic use-case is roughly as follows:
```
julia> sig = (Tuple{G} where G)
Tuple{G} where G
julia> Base.rewrap_unionall.(DocStringExtensions.uniontypes(Base.unwrap_unionall(sig)), sig)
1-element Vector{DataType}:
Tuple{G}
julia> Base.rewrap_unionall.(DocStringExtensions.uniontypes(Base.unwrap_unionall(sig)), Ref(sig))
1-element Vector{UnionAll}:
Tuple{G} where G
```
I chose to avoid the `Ref(...)`-style broadcast-prevention; materializing a vector right away reads much better here.
> fix broadcast on `Base.rewrap_unionall` in `alltypesigs`

- .github/workflows/ci.yml
CI runs were getting double triggered on each PR
> Only run CI `push` trigger when on `master`/tags

- src/DocStringExtensions.jl
- src/templates.jl
- src/utilities.jl
- test/interpolation.jl
- test/tests.jl
Should help handle #54, and possibly make other things easier to handle, such as #19 and other places where digging into the lowered code is a pain while dealing with the raw `Expr` would be more useful.
This intercepts documented expressions during macro expansion of `Core.@doc` and makes the documented `Expr` available for capturing and usage in abbreviation objects.
> Support capturing `Expr` for use in abbreviations.

- src/templates.jl
It wasn't 100% clear to me what the `@template` actually does from the docstring, and I hope that this clarifies it a bit. I guess, mainly, it was unclear what it means to "apply" the template.
> Add clarification to at-template docstring

- .github/workflows/ci.yml
- test/tests.jl
Alternative to #167. It looks like there has been a bugfix in 1.10, and the auto-generated methods when you have positional arguments with default values:
https://github.com/JuliaDocs/DocStringExtensions.jl/blob/ec66ad4a472241c7a7ae0686247fe578c5e50210/test/TestModule/M.jl#L7
On 1.9:
```
julia> methods(M.g)
[1] g()
@ ~/juliadocs/clones/DocStringExtensions.jl/test/TestModule/M.jl:7
[2] g(x)
@ ~/juliadocs/clones/DocStringExtensions.jl/test/TestModule/M.jl:7
[3] g(x, y)
@ ~/juliadocs/clones/DocStringExtensions.jl/test/TestModule/M.jl:7
[4] g(x, y, z; kwargs...)
@ ~/juliadocs/clones/DocStringExtensions.jl/test/TestModule/M.jl:7
```
vs on 1.10:
```
julia> methods(M.g)
[1] g(; ...)
@ ~/juliadocs/clones/DocStringExtensions.jl/test/TestModule/M.jl:7
[2] g(x, y, z; kwargs...)
@ …
```
> Fix tests on Julia 1.10+

- .github/workflows/ci.yml
- Project.toml
- src/DocStringExtensions.jl
- src/utilities.jl
- test/runtests.jl
- test/tests.jl
This removes the `LibGit2` dependency, which was initially added back in https://github.com/JuliaDocs/DocStringExtensions.jl/pull/4 do deal with Travis not using an actual git repo as the build directory. We had to vendor `Base.url` which brought in the `LibGit2` dep. Instead change the logic in the `url` wrapper function to check whether Travis is the likely environment and generate an URL based solely on it's env vars, otherwise just use `Base.url` directly and whatever it's result is.
When `LibGit2` isn't actually loaded (https://github.com/JuliaLang/julia/blob/08c87b20993dc969f42b1a6eb50b931c66f311de/base/methodshow.jl#L393-L395) then of course `Base.url` won't return what's needed, and maybe that's fine since you can just ensure `LibGit2` is loaded in the process. This seems more …
> Remove `LibGit2` dependency

- Project.toml
- src/utilities.jl
- test/tests.jl
Method table internals changed in https://github.com/JuliaLang/julia/commit/1735d8f03c9e4fedba652e4e562c049ac48c93fd, breaking our former reliance on `(::MethodList).mt`.
The associated error was originally observed [here](https://github.com/JuliaGPU/Vulkan.jl/actions/runs/15362623850/job/43231635465#step:7:329).
> Fixes for nightly
